---
title: "Life_Table"
author: "Zhuodiao Kuang"
date: "`r Sys.Date()`"
output: github_document
---

# Load packages

```{r}
library(survival)
library(tidyverse)
library(ggfortify)
library(dplyr)
library(ggplot2)
library(biostat3)
```


# Ovarian Cancer:

* futime: survival or censoring time(day)
* fustat: censoring status(censor = 0)
* age: in years
* resid.ds: residual disease present(1=no, 2=yes)
* rx: treatment group
* ecog.ps: ECOG performance status(1 is better)

```{r ovarian, message=FALSE, warning=FALSE}

data("ovarian")
attach(ovarian)
ovarian_rx1 <- ovarian |>
  filter(rx == 1) |>
  arrange(futime)

ovarian_rx2<- ovarian |>
  filter(rx == 2)|>
  arrange(futime)

ovarian_rx1
ovarian_rx2
```

# Create life-table stratified by rx

```{r}
print(lifetab2(Surv(futime, fustat == 0)~1,ovarian_rx1), digits = 2)
print(lifetab2(Surv(futime, fustat == 0)~1,ovarian_rx2), digits = 2)
```

# Plot hazard function by rx based on life-table estimate

```{r}
ovarian.survfit <-
  survfit(Surv(futime, fustat)~rx,data= ovarian)

ovarian.survfit |>
  autoplot() +
  ylab("S(t)") +
  xlab("Time")
```

# Create life-table stratified by rx
```{r}
res <- summary( survfit( Surv(futime, fustat)~rx, data=ovarian))
cols <- lapply(c(2:6, 8:11) , function(x) res[x])
tbl <- do.call(data.frame, cols)
tbl
```
